version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    minimum-release-age:
      days: 3
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    minimum-release-age:
      days: 3
